################################# Default configuration ###################
# provide your domain here
baseURL = "https://syscor-homologacao.before.com.br/faq"
# theme
theme = "dot"
# site title
title = "Vivo GO FAQ"
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)

# unsafe html
[markup.goldmark.renderer]
unsafe= true

################################# navigation ################################
[[menu.main]]
name = "Manuais"
url = "https://before.atlassian.net/wiki/spaces/SYSCOR/overview"
weight = 1
target = "_blank"

[[menu.main]]
name = "Contato"
url = "contato"
weight = 2
target = "_self"

############################# Default Parameters ##########################
[params]
# logo is for all page
logo = "images/logo.png"
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#591580"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
text_white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

############################## social links ##############################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/beforeTI/"
  
[[params.social]]
icon = "ti-twitter" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/beforeti"

[[params.social]]
icon = "ti-instagram" # themify icon pack : https://themify.me/themify-icons
link = "https://www.instagram.com/before.ti/"
  
[[params.social]]
icon = "ti-world" # themify icon pack : https://themify.me/themify-icons
link = "https://before.com.br/"

################################ Language ######################
[Languages.en]
languageName = "PT (BR)"
languageCode = "pt-br"
weight = 1

# banner
[Languages.en.params.banner]
title = "Como podemos ajudar você?"
bg_image = "images/banner.jpg"
subtitle = "Você também pode acessar os tópicos abaixo para encontrar o que está procurando"
placeholder = "Digite as palavras-chave para encontrar sua resposta"

# call to action
[Languages.en.params.cta]
enable = true
title = "Não encontrou uma resposta para a sua dúvida?"
content = "Envie sua dúvida para a nossa equipe de suporte pelo e-mail cs.vivogo@before.com.br.<br><br>Em breve retornaremos seu contato."